### ISSUE TITLE
Error in main.py : line 50, "v" not defined

### ISSUE THREAD

**Issue by SurajSubramanian** [srcecde/python-youtube-api#12]
This is the full error message when file is executed using : 
```python3
python-youtube-api-master % python3 main.py --c --max 10 --videourl https://youtu.be/y_j-r8x1FtI --key AAAAAA
```
(Here i used copy video url after right clicking on video
```
Traceback (most recent call last):
  File "main.py", line 59, in <module>
    main()
  File "main.py", line 50, in main
    vid = q["v"][0]
KeyError: 'v'
```

Error message when i execute using the same command in the ReadME file : 
```python3
python3 main.py --c --max 10 --videourl https://www.youtube.com/watch?v=y_j-r8x1FtI --key AAAAAAA
```

```
zsh: no matches found: https://www.youtube.com/watch?v=y_j-r8x1FtI
```

**Comment by srcecde** [comment]
Try to keep the URL in double-quotes. Something like this.

`python3 main.py --c --max 10 --videourl "https://www.youtube.com/watch?v=y_j-r8x1FtI" --key AAAAAAA`
